version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: keuangan_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: db_keuangan
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Baris ini yang "menyuntikkan" skrip SQL kamu ke dalam Docker
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: